name: debian

on: [ workflow_dispatch ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v3
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      -
        name: Docker Buildx (build) - debian
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag collelog/buildenv:debian \
            --file ./debian.Dockerfile ./
      -
        name: Docker Buildx (push) - debian
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag collelog/buildenv:debian \
            --file ./debian.Dockerfile ./
      -
        name: Docker Check Manifest - debian
        run: |
          docker run --rm mplatform/mquery collelog/buildenv:debian
      -
        name: Docker Buildx (build) - debian-jst
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=false" \
            --tag collelog/buildenv:debian-jst \
            --file ./debian-jst.Dockerfile ./
      -
        name: Docker Buildx (push) - debian-jst
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --platform linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64 \
            --output "type=image,push=true" \
            --tag collelog/buildenv:debian-jst \
            --file ./debian-jst.Dockerfile ./
      -
        name: Docker Check Manifest - debian-jst
        run: |
          docker run --rm mplatform/mquery collelog/buildenv:debian-jst
      -
        name: Clear
        if: always()
        run: |
          rm -f ${HOME}/.docker/config.json
